
package dfrs.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DFRSServerNDLService", targetNamespace = "http://server.dfrs", wsdlLocation = "http://localhost:1052/dfrs?wsdl")
public class DFRSServerNDLService
    extends Service
{

    private final static URL DFRSSERVERNDLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DFRSSERVERNDLSERVICE_EXCEPTION;
    private final static QName DFRSSERVERNDLSERVICE_QNAME = new QName("http://server.dfrs", "DFRSServerNDLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1052/dfrs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DFRSSERVERNDLSERVICE_WSDL_LOCATION = url;
        DFRSSERVERNDLSERVICE_EXCEPTION = e;
    }

    public DFRSServerNDLService() {
        super(__getWsdlLocation(), DFRSSERVERNDLSERVICE_QNAME);
    }

    public DFRSServerNDLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DFRSSERVERNDLSERVICE_QNAME, features);
    }

    public DFRSServerNDLService(URL wsdlLocation) {
        super(wsdlLocation, DFRSSERVERNDLSERVICE_QNAME);
    }

    public DFRSServerNDLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DFRSSERVERNDLSERVICE_QNAME, features);
    }

    public DFRSServerNDLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DFRSServerNDLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDFRSService
     */
    @WebEndpoint(name = "DFRSServerNDLPort")
    public IDFRSService getDFRSServerNDLPort() {
        return super.getPort(new QName("http://server.dfrs", "DFRSServerNDLPort"), IDFRSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDFRSService
     */
    @WebEndpoint(name = "DFRSServerNDLPort")
    public IDFRSService getDFRSServerNDLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dfrs", "DFRSServerNDLPort"), IDFRSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DFRSSERVERNDLSERVICE_EXCEPTION!= null) {
            throw DFRSSERVERNDLSERVICE_EXCEPTION;
        }
        return DFRSSERVERNDLSERVICE_WSDL_LOCATION;
    }

}
