
package dfrs.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DFRSServerMTLService", targetNamespace = "http://server.dfrs", wsdlLocation = "http://localhost:1050/dfrs?wsdl")
public class DFRSServerMTLService
    extends Service
{

    private final static URL DFRSSERVERMTLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DFRSSERVERMTLSERVICE_EXCEPTION;
    private final static QName DFRSSERVERMTLSERVICE_QNAME = new QName("http://server.dfrs", "DFRSServerMTLService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1050/dfrs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DFRSSERVERMTLSERVICE_WSDL_LOCATION = url;
        DFRSSERVERMTLSERVICE_EXCEPTION = e;
    }

    public DFRSServerMTLService() {
        super(__getWsdlLocation(), DFRSSERVERMTLSERVICE_QNAME);
    }

    public DFRSServerMTLService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DFRSSERVERMTLSERVICE_QNAME, features);
    }

    public DFRSServerMTLService(URL wsdlLocation) {
        super(wsdlLocation, DFRSSERVERMTLSERVICE_QNAME);
    }

    public DFRSServerMTLService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DFRSSERVERMTLSERVICE_QNAME, features);
    }

    public DFRSServerMTLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DFRSServerMTLService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IDFRSService
     */
    @WebEndpoint(name = "DFRSServerMTLPort")
    public IDFRSService getDFRSServerMTLPort() {
        return super.getPort(new QName("http://server.dfrs", "DFRSServerMTLPort"), IDFRSService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDFRSService
     */
    @WebEndpoint(name = "DFRSServerMTLPort")
    public IDFRSService getDFRSServerMTLPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.dfrs", "DFRSServerMTLPort"), IDFRSService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DFRSSERVERMTLSERVICE_EXCEPTION!= null) {
            throw DFRSSERVERMTLSERVICE_EXCEPTION;
        }
        return DFRSSERVERMTLSERVICE_WSDL_LOCATION;
    }

}
