
package dfrs.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IDFRSService", targetNamespace = "http://server.dfrs/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IDFRSService {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns dfrs.client.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferReservation", targetNamespace = "http://server.dfrs/", className = "dfrs.client.TransferReservation")
    @ResponseWrapper(localName = "transferReservationResponse", targetNamespace = "http://server.dfrs/", className = "dfrs.client.TransferReservationResponse")
    @Action(input = "http://server.dfrs/IDFRSService/transferReservationRequest", output = "http://server.dfrs/IDFRSService/transferReservationResponse")
    public Result transferReservation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookedFlightCount", targetNamespace = "http://server.dfrs/", className = "dfrs.client.GetBookedFlightCount")
    @ResponseWrapper(localName = "getBookedFlightCountResponse", targetNamespace = "http://server.dfrs/", className = "dfrs.client.GetBookedFlightCountResponse")
    @Action(input = "http://server.dfrs/IDFRSService/getBookedFlightCountRequest", output = "http://server.dfrs/IDFRSService/getBookedFlightCountResponse")
    public String getBookedFlightCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns dfrs.client.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editFlightRecord", targetNamespace = "http://server.dfrs/", className = "dfrs.client.EditFlightRecord")
    @ResponseWrapper(localName = "editFlightRecordResponse", targetNamespace = "http://server.dfrs/", className = "dfrs.client.EditFlightRecordResponse")
    @Action(input = "http://server.dfrs/IDFRSService/editFlightRecordRequest", output = "http://server.dfrs/IDFRSService/editFlightRecordResponse")
    public Result editFlightRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllFlightInfo", targetNamespace = "http://server.dfrs/", className = "dfrs.client.GetAllFlightInfo")
    @ResponseWrapper(localName = "getAllFlightInfoResponse", targetNamespace = "http://server.dfrs/", className = "dfrs.client.GetAllFlightInfoResponse")
    @Action(input = "http://server.dfrs/IDFRSService/getAllFlightInfoRequest", output = "http://server.dfrs/IDFRSService/getAllFlightInfoResponse")
    public String getAllFlightInfo();

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns dfrs.client.Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookFlight", targetNamespace = "http://server.dfrs/", className = "dfrs.client.BookFlight")
    @ResponseWrapper(localName = "bookFlightResponse", targetNamespace = "http://server.dfrs/", className = "dfrs.client.BookFlightResponse")
    @Action(input = "http://server.dfrs/IDFRSService/bookFlightRequest", output = "http://server.dfrs/IDFRSService/bookFlightResponse")
    public Result bookFlight(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

}
